### ISSUE TITLE
很棒

### ISSUE THREAD

**Issue by Xdy1579883916** [BlackGlory/eternity#15]
写的不错，建议进一步完善仓库，如果不准备上服务市场，可以提供构建完成的zip产物，在没有开发环境的电脑想试用软件的时候，有点不方便。

**Comment by BlackGlory** [comment]
很有道理, 刚刚把当前版本作为v0.2.0发布了: [Release v0.2.0](https://github.com/BlackGlory/eternity/releases/tag/v0.2.0).
这个项目没有发布到应用商店是因为我觉得Manifest V3的相关设计还不完善, 并且大多数人的需求已经可以通过油猴搞定了.

**Comment by Xdy1579883916** [comment]
油猴是很强，但是不开源，不支持esm。

我爱惨了你的插件设计。原本公司业务有个插件，走的路子和你这个差不多esm的，不过那个时候还没有userscripts选项，通过向主世界插入mudule模块实现的，饱受CSP限制。 

我把我的插件“基座”打开，为页面提供必要方法，再把原本需要自己插件注入的主import导入，写到你的脚本里面，然后一行代码就无缝跑起了我的项目（当然这里面还有一些小问题）

一行代码喂，我就像做梦一样，还得到了一个与主世界隔离的能力，之前总是和主世界有内置函数冲突（有的网站会重写一些内置方法）
